### ISSUE TITLE
Factor out emicklei/proto

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#1]
The Golang Protobuf parsing library github.com/emicklei/proto has done wonders for Prototool, and this project would not exist without it - when I started Prototool, it was originally conceived as just a linter for Uber to keep us on a common standard, and the prototype solely used this library. I can't thank Ernest Micklei enough.

However, Prototool has grown into something much larger, and emicklei/proto does not fully implement the Protobuf spec - [we explicitly need to check against protoc](https://github.com/emicklei/proto/issues/14) to verify a file compiles before linting or formatting, and cleaning up edge cases in emicklei/proto has been a case of [exception-driven development](https://github.com/emicklei/proto/issues?q=is%3Aissue+is%3Aclosed). Along the way, the `internal/x/protoc` package picked up the ability to compile Protobuf files on the fly and provide a full [FileDescriptorSet](https://github.com/google/protobuf/blob/1a7a7fca804afa1cf67f8be5e71092898ba40334/src/google/protobuf/descriptor.proto#L56) to Prototool packages, which a lot of the functionality within Prototool relies on. If [SourceCodeInfo](https://github.com/google/protobuf/blob/1a7a7fca804afa1cf67f8be5e71092898ba40334/src/google/protobuf/descriptor.proto#L717) was also outputted (easily done by adding `--include_imports --include_source_info` to `protoc` calls) then we could effectively replicate the functionality of Prototool.

There's a few options here:

- Factor out emicklei/proto and build a new set of `Message/Service/Enum/etc` structs/interfaces based on `FileDescriptorSets/SourceCodeInfo`.
- Factor out emicklei/proto and use `FileDescriptorSets/SourceCodeInfo` to use the existing setup in https://godoc.org/github.com/jhump/protoreflect/desc. There's a few things missing in the descriptors there, like source representation for options and the ability to walk descriptors in order they appear in the file, but if we're going to factor out emicklei/proto this is probably the best option as we use jhump/protoreflect elsewhere and that probably isn't going away.
- Keep emicklei/proto and say it's "good enough". At least in the short-term, this might be the option we take. emicklei/proto now works against all of [googleapis](https://github.com/googleapis/googleapis) so it's pretty complete, and we only use it in `internal/x/lint` and `internal/x/format`, so we might just keep it for now.

**Comment by amckinney** [comment]
Seeing as this is a fairly large undertaking, we should consider your last suggested approach to simply keep `emicklei/proto` and say it's "good enough". This is definitely not ideal, but it realistically won't be prioritized in the near future.

I would suggest closing this issue for now - we can re-open this if it turns into a more-pressing issue.
