### ISSUE TITLE
Remove unneeded config options/Rename some config options

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#12]
Similar to #11, we need a full review of the `prototool.yaml` config file. It exposes way too much functionality for v1.0 in my opinion. See `etc/config/example/prototool.yaml` for all options.

Things I nominate for potential deletion:

- no_default_excludes: I exclude "vendor" by default to make this easy to use with Golang projects, but this is probably overkill and too Golang-specific. Just removing the concept of default excludes altogether would be nice.
- protoc_include_wkt: Maybe just always include the Well-Known Types?
- format: The entire section. There shouldn't be options for formatting, ie "choose your spacing", no. I added this for testing.

Things I'm unsure of:

- lint groups: Will explain in a different issue.
- gen.plugins.type: Going with #2, do we need this? We might for Golang plugins that are not well-known, but this concept is weird.

**Comment by amckinney** [comment]
Several of the previously supported configuration options are now removed. A lot of the implementation was left as-is so that they can be easily re-introduced after a 1.0 release.
