### ISSUE TITLE
Warnings emitted by protoc plugins are failing the generation process

### ISSUE THREAD

**Issue by utrack** [uber/prototool#128]
My plugin emits a warning to stderr, but exits with code 0 and no `Error` in the `MessageResponse` - however, `prototool` treats it as unrecoverable error.
```
prototool all "endpoint/"
2018-06-24T22:11:33.431+0300    WARN    protoc returned a line we do not understand, please file this as an issue at https://github.com/uber/prototool/issues/new       {"protocLine": "I0624 22:11:33.429160   27601 handler.go:81] service/itemapi/itemapipb/client.proto: no target service defined in the file"}
<input>:1:1:I0624 22:11:33.429160   27601 handler.go:81] service/itemapi/itemapipb/client.proto: no target service defined in the file
make: *** [Makefile:54: gen] Error 255
```

**Comment by peter-edge** [comment]
This is by design - plugins generally do not have output unless there is a failure. We fail if there's output to handle this general case - for example, unused imports is not a failure for `protoc`, but we want to fail it for `prototool`.

I would close this as "working as intended," but there may be some way we want to handle this, maybe saying if a plugin (not `protoc`) returns 0, we just log output as warning lines and exit 0 in `prototool`.

What plugin is this, and how can I reproduce this?

**Comment by utrack** [comment]
It's generated by https://github.com/utrack/clay/tree/master/cmd/protoc-gen-goclay.
I can silence the warning since we want to work with prototool badly ( :) ), but specs said that either (warning and non-0 code) OR (`MessageResponse.Error` non empty and any exit code) mean that the generation had failed.

It can be replicated by using the generator on any file w/ declared RPC, but without any `google.api.http` options declared - https://github.com/utrack/clay/blob/master/doc/example/pb/sum.proto w/o importing `sum.yaml` should work.

**Comment by peter-edge** [comment]
It sounds like the main issue is the plugin doing something that (in my experience) is non-standard: printing output on success. I’m guessing that the plugin is printing this warning because nothing will be generated? Thr general thing to do is print nothing and just exit 0.

**Comment by utrack** [comment]
It's not a typical thing to do, but I don't think logging should be prohibited. I might be wrong, but plugin errors are signaled exclusively via `Error` field of `CodeGeneratorResponse` and optionally exit code in case input is malformed: https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto#L107

If protoc receives `.Error` or non-0 it prints an error and exits with non-zero exit code as well AFAIK.

**Comment by peter-edge** [comment]
If you can provide me a branch of some repository (probably clay), with the necessary setup to reproduce, I can investigate further.

**Comment by peter-edge** [comment]
I've done more investigation - with how Prototool is set up, there's no fundamentally good way to handle this.

We want to assume that output from the `protoc` invocation means failure, see https://github.com/uber/prototool/blob/43fb0e7a3b849ee691d8fe8ccdb09c19ce66ad0e/internal/protoc/compiler.go#L230 and https://github.com/uber/prototool/blob/43fb0e7a3b849ee691d8fe8ccdb09c19ce66ad0e/internal/protoc/compiler.go#L515 . For cases like unused imports, even if `protoc` exits with 0, we want to fail. There's no way to differentiate between "good" output and "bad" output from `stderr` from a plugin. As an example, here's a dummy plugin I made called `protoc-gen-dummy`:

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintln(os.Stderr, "dummyOutput")
}
```

If I run `prototool gen` with a configuration that invokes this (the plugin is installed as `protoc-gen-dummy`), I get:

```
2018-06-26T11:27:52.888+0200	WARN	protoc returned a line we do not understand, please file this as an issue at https://github.com/uber/prototool/issues/new	{"protocLine": "dummyOutput"}
<input>:1:1:dummyOutput
```

This means the output was not prefixed by `protoc-gen-dummy` or the like, and the line `dummyOutput` was just copied to the `stderr` of `protoc`. In theory, we could treat any unknown output as OK output, assuming that `protoc` exited with 0, that is one option, but see #14, that will probably result in more false negatives, whereas the current situation results in a few false positives, namely this case.

Generally, a `protoc` plugin should not produce output. While the spec for plugins says the above, this isn't how Prototool is intended to operate, and Prototool works with most known plugins. We want to parse all output and handle it within Prototool, and it would probably be better to update `protoc-gen-clay` to not produce such warnings.

**Comment by peter-edge** [comment]
@AlexAPB for a second opinion about whether to either 1. not fail if there is output but `protoc` exits with 0, which may result in dropped failures/false negatives, or 2. still fail if there is output

**Comment by peter-edge** [comment]
I put the `protoc-gen-dummy` code on the `protoc-gen-dummy` branch:

https://github.com/uber/prototool/tree/protoc-gen-dummy

```
$ git diff --stat dev
 .gitignore                            |  1 +
 Makefile                              |  1 +
 example/idl/uber/prototool.yaml       |  2 ++
 internal/cmd/protoc-gen-dummy/main.go | 10 ++++++++++
 4 files changed, 14 insertions(+)
```

**Comment by utrack** [comment]
Well, dang. :)
Most of the strings described in #14 are actually warnings - the code is still being generated, ex. "import not used" or "no syntax specified".

For example, code is still being generated after warnings 
```
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: sum.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
sum.proto: warning: Import google/protobuf/timestamp.proto but not used.
```
If there's an error in proto syntax then protoc exits with non-zero,`sum.proto:33:3: Expected "required", "optional", or "repeated".` returns code 1.

**Comment by peter-edge** [comment]
A quick recommendation - you could add a `--no-stderr` flag to `protoc-gen-clay`, that redirects `stderr` to `ioutil.Discard` (not sure how easy this is with glog, but generally probably better to switch out glog to something else anyways haha, may I recommend github.com/uber-go/zap). Then, in your `prototool.yaml`, just set:

```yaml
- name: clay
  type: go
  flags: no-stderr=true
  output: path/to/output
```

**Comment by utrack** [comment]
Oh, I see - it makes sense if you're enforcing strictness by design. :)
Thank you, guess I'll do just that.

**Comment by AlexAPB** [comment]
looks like I'm late to this ticket, but since my opinion was asked here: @peter-edge I'm in favour of keeping it strict since it's the common case for plugins to be silent on success.
