### ISSUE TITLE
Add tool to check for breaking changes

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#131]
https://github.com/nilslice/protolock just came out recently, and this is a nice tool, but it would be nice if similar functionality was built into Prototool. Additionally, Protolock generates a `proto.lock` file that stores information on the Protobuf files in a repository, which I'd like to get rid of. This is a new format and inherently can have bugs, but more to the point is duplicated information - the `proto.lock` file is generated via the checked-in Protobuf files, which in turn contain all the information you need. If you were to generate a `FileDescriptorSet` for the current Protobuf files, and a `FileDescriptorSet` for the old Protobuf files, and then compare the two, you could get the same thing. A `proto.lock` file could have just been the result of `--descriptor_set_out` as a further example, and then used https://github.com/jhump/protoreflect, but again instead of storing another file, we can just generate this on the fly. I'd also like errors to be printed in the Prototool standard `filename:line:column:message` format.

Example of what I'd imagine:

```
prototool check-compatibility --from dev # dev is the name of the base branch
a/b/c.proto:3:4:Cannot remove field "foo".
a/b/d.proto:1:1:Cannot change syntax.
...
```

**Comment by AlexAPB** [comment]
Related: #219

**Comment by peter-edge** [comment]
This is done in https://github.com/uber/prototool/pull/279. You can use this on dev:

```
prototool break check --git-tag TAG # check against this tag
prototool break check --git-branch BRANCH # check against this branch
prototool break check path/to/protodir --git tag TAG # check against this tag for subdir path/to/protodir
prototool break check # check against the default branch
prototool break check path/to/protodir # check against the default branch for subdir path/to/protodir
```

More documentation to follow. Packages of the form `foo.bar.vMAJORbetaBETA` where MAJOR >=1 and BETA >= 1 are ignored unless the `--include-beta` flag is added.

**Comment by peter-edge** [comment]
See https://github.com/uber/prototool/pull/382 for additional workflows
