### ISSUE TITLE
Factor out zap logging

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#15]
We used github.com/uber-go/zap for logging, which is fine as long as this is just a CLI tool, but as we learned the hard way in github.com/grpc/grpc-go, it's not great to assume a given logging library unless you need to. The logging in Prototool is very basic, and almost always at the debug level, so creating a minimal package similar to https://godoc.org/google.golang.org/grpc/grpclog (but even simpler) might be nice.

**Comment by peter-edge** [comment]
I think we should close this @amckinney @AlexAPB

**Comment by AlexAPB** [comment]
Sounds good to me, our choice of logger is purely internal so we can switch it out later if need be.
