### ISSUE TITLE
External API

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#17]
We need to agree on how to expose a Golang external API for library usage. We need this for [yab](https://github.com/yarpc/yab) for example. This will probably be something similar to `internal/x/exec.Runner`, but with actual inputs and return values, as opposed to printing to stdout.

**Comment by misfer108** [comment]
Hi

**Comment by misfer108** [comment]
[Getting Started.pdf](https://github.com/uber/prototool/files/1900742/Getting.Started.pdf)

**Comment by peter-edge** [comment]
We don't need this for v1.0, and this isn't really an issue per se, we'll split things out as we need them.
