### ISSUE TITLE
Client/server implementation for Prototool as a service

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#18]
This probably won't happen, but just for discussion.

In [Protoeasy](https://go.pedge.io/protoeasy), I made it possible to run Protoeasy as a server with a given docker container (which also had versions of all known plugins) so there was no need to install anything locally. This was useful when it was not as trivial to install protoc, and was also useful for installing things like golang/protobuf grpc-gateway in a consistent manner. This worked using https://github.com/peter-edge/protoeasy-go/blob/master/protoeasy.proto by tarring up all `.proto` files in your context, sending the tarball to the server, running the generation logic, then tarring up the entire result, and untarring in your local context.

Not sure if we want something similar here. Prototool handles installing protoc for you, which is easier now with GitHub releases. Depending on what we do with #2, we might want this to make it easy for known plugins to be handled as well.

**Comment by peter-edge** [comment]
I think we should close this @amckinney @AlexAPB

**Comment by AlexAPB** [comment]
Yeah let's close this too, I think this is fairly out of scope for what we envision prototool to be.
