### ISSUE TITLE
Feature request: Ability to generate only one language

### ISSUE THREAD

**Issue by mickeyreiss** [uber/prototool#185]
I have a prototool config that generates many languages protos. Sometimes, I want to save some time and just regenerate a single language. Would it be possible to add this option? I'd expect something like

    prototool gen --only go
    prototool gen --skip go
    prototool gen --only go,java

**Comment by peter-edge** [comment]
Can you share concrete numbers, just because I am interested? And the plugins you’re using? I’ve used prototool on large repos and it takes on the order of 1/3 of a second, so I’m wondering if something else is going on.

**Comment by mickeyreiss** [comment]
Aha, it seems that our makefile is inefficient (due to pbjs/pbts being slow), but `prototool gen` is sub one second. 

A few other concerns that led to submitting this issue:
- When building thin docker containers, we'd like to avoid dealing with unrelated files.
- We have custom protoc plugins written in python and typescript; these require some environment setup.

I suppose "save time" for these two refers more to dev effort than compute.

Thanks!

**Comment by peter-edge** [comment]
Yea I get th feature request in practice, my general opinion though is that I want prototool to bauscally generate a consistent view of the world across all plugins, so there’s no mismatch. The main use case is you have your protobuf api repo that is a dependency of your clients and servers, and you effectively provide an SDK using prototool to generate consistent stubs across all languages. So allowing only one language to be generated means you’ll have inconcistent state.

For your custom plugins, can you make a docker container that is sufficiently fast to build when cached, and do that?

**Comment by peter-edge** [comment]
Also for you thin docker containers, just build thin with a .dockerignore right?

**Comment by peter-edge** [comment]
@mickeyreiss can we close this? Let me know.

**Comment by mickeyreiss** [comment]
Yep we'll take your feedback into account and come back here if we have a more compelling use case.
