### ISSUE TITLE
Installation of known plugins

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#19]
In #2 we describe the wanted functionality of handing known plugins. We install `protoc` for you within  Prototool. It would be nice for Prototool to handle installation of things like `protoc-gen-go` as well. A problem here is that you want your library code to match your generated code, so it might be better for you to do:

```
.PHONY: gen
gen:
  go install ./vendor/github.com/golang/protobuf/protoc-gen-go
  prototool gen
```

So this might end up causing more problems than it solves. This is worth discussion though.

**Comment by utrack** [comment]
I think it would be out of scope - generators can be pinned via `vgo` per project, for example.

If you install it via `vgo install <generator>` then it'll install `<generator>` of a version that's being referenced in `go.mod` of a current project - it should be supported as well if plugin installation feature can't be disabled.

**Comment by peter-edge** [comment]
For Golang plugins this will work, for non-Golang plugins it won't.

**Comment by peter-edge** [comment]
Having thought more about this, I think this is out of scope for Prototool.
