### ISSUE TITLE
Homebrew Formula and Bottle

### ISSUE THREAD

**Issue by abhinav** [uber/prototool#203]
We should make prototool easily installable by providing a Homebrew Formula
and Bottle. We can create our own Tap or place it in the default Formulae
collection (homebrew-core). An advantage of our own Tap is that the complete
release can happen in one go versus waiting on homebrew-core to accept the
change.

Ideally, updating the Formula and the Bottle is automated as part of some
release script.

This isn't really high priority and we can defer it until there's more demand
for it.

**Comment by peter-edge** [comment]
I put together https://github.com/uber/prototool/pull/205 - as opposed to fragmenting the conversation, I put some thoughts on this issue over there. Take a look when you have time! :-)
