### ISSUE TITLE
[Question] When running `prototool . -wf` is there any way to not prepend `com.` to the java package?

### ISSUE THREAD

**Issue by sorenbug** [uber/prototool#222]
I want my protobuf package to be `xyz.degreetech` and not `com.xyz.degreetech`; in cases of `xyz.degreetech.foo`, not `com.xyz.degreetech.foo`.

**Comment by peter-edge** [comment]
Do you mean `prototool format -wf`? There's no way to do this if you are using the `--fix` flag. Per the [documentation](https://github.com/uber/prototool#prototool-format), the `--fix` flag is meant to update your Protobuf file options to match the default [Style Guide](https://github.com/uber/prototool/blob/dev/etc/style/uber/uber.proto), which roughly matches the [Google Cloud APIs file structure](https://cloud.google.com/apis/design/file_structure). We don't see ourselves providing alternative formats - Prototool is meant to be opinionated on this matters to provide consistency across a large number of Protobuf files without allowing much deviation in terms of style.
