### ISSUE TITLE
error on prototool lint .

### ISSUE THREAD

**Issue by Soypete** [uber/prototool#228]
2018-09-10T17:20:22.605-0600	WARN	protoc returned a line we do not understand, please file this as an issue at https://github.com/uber/prototool/issues/new	`{"protocLine": "golang/protobuf/protoc-gen-go/testdata/extension_user.proto: \"extension_base.BaseMessage\" seems to be defined in \"golang/protobuf/protoc-gen-go/testdata/extension_base.proto\", which is not imported by \"golang/protobuf/protoc-gen-go/testdata/extension_user.proto\".
<input>:1:1:Import "extension_extra.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto" was not found.
<input>:1:1:Import "multi/multi1.proto" was not found.
<input>:1:1:Import "multi/multi2.proto" was not found.
<input>:1:1:Import "multi/multi3.proto" was not found.
<input>:1:1:Import "testdata/test.proto" was not found.
<input>:1:1:golang/protobuf/protoc-gen-go/testdata/extension_user.proto: "extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/proto/proto3_proto/proto3.proto:1:1:"testdata.SubDefaults" is not defined.
golang/protobuf/proto/proto3_proto/proto3.proto:61:3:"testdata.SubDefaults" is not defined.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:45:8:"extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:50:8:"extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:55:8:"extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:62:10:"extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:70:10:"extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:76:8:"extension_base.BaseMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.
golang/protobuf/protoc-gen-go/testdata/extension_user.proto:94:10:"extension_base.OldStyleMessage" seems to be defined in "golang/protobuf/protoc-gen-go/testdata/extension_base.proto", which is not imported by "golang/protobuf/protoc-gen-go/testdata/extension_user.proto".  To use it here, please add the necessary import.`

**Comment by Soypete** [comment]
I don't know what this means... but I want it to work

**Comment by AlexAPB** [comment]
Can you share what the contents of your `prototool.yaml` and `.proto` file?

**Comment by peter-edge** [comment]
@Soypete per the [Issue Guidelines](https://github.com/uber/prototool/blob/dev/.github/ISSUE_TEMPLATE.md), bug reports should contain steps to reproduce the issue. I'll leave it up to @AlexAPB @amckinney whether to close this, but generally we will close GitHub issues that don't provide this (which doesn't mean give up! it's just an indicator that we need more information, which if provided, feel free to reopen).

**Comment by AlexAPB** [comment]
Closing for now. Feel free to re-open if you can provide more information.
