### ISSUE TITLE
Lint proto path

### ISSUE THREAD

**Issue by jhaals** [uber/prototool#229]
Hi!

I've created a path lint check at https://github.com/uber/prototool/compare/dev...jhaals:pathlint?expand=1

It verifies that protos with the package `package mycorp.foobar.v1` are stored in `/whatever/start/path/mycorp/foobar/v1`. I want to double check if this is of interest before fixing breaking tests due to the introduction of this linter.

**Comment by jhaals** [comment]
Hi Peter,
I verified and there's no problem with either `prototool lint .`(repo root) or `prototool lint repo`. However you can't be standing _inside_ foo/bar/baz and perform the lint.

I wasn't aware of the includes. I tried including protos from another path but no lints where performed on those, not sure if that's by design or me including path the wrong way.
```
protoc:
  includes:
    - /tmp/foo
```

I completely understand your reasoning regarding having this as a default linter, checking directory base name sounds like a good middle ground.
There's no rush in adding this linter, we could create an internal build with this linter or simply wait for a public lint API.

**Comment by peter-edge** [comment]
@jhaals I think I'm going to close this as "wontfix" - Prototool will remain 100% backwards compatible and the default linter set won't change, but we're working on a v2 (opt-in, not opt-out, to remain backwards compatible) of the lint rules that more closely match the Google Cloud APIs file structure https://cloud.google.com/apis/design/file_structure including adding major versions to packages. See #247 for the start of this work. As such, this linter you're proposing would have to change and/or double - it's a lot of work. Let me know if you disagree.
