### ISSUE TITLE
Why not use `filepath.Clean(filepath.Join(genGoPluginOptions.ImportPath, filepath.Dir(path)))`

### ISSUE THREAD

**Issue by lidalei** [uber/prototool#233]
In https://github.com/uber/prototool/blob/00507d9086f93f0814a9ac910c4cded6440826c6/internal/protoc/compiler.go#L474, I am wondering why it is not using `filepath.Clean(filepath.Join(genGoPluginOptions.ImportPath, filepath.Dir(path)))` so that the `genPlugin.OutputPath.RelPath` becomes just defines the path to put the generated Go files.

**Comment by lidalei** [comment]
For example I have protos like this

a/prototool.yaml
a/c/e.proto
a/c/f.proto
Assuming in e.proto, f.proto is imported.
If I set `ImportPath ` as `github.com` and `OutputPath ` as `./gen-go`, the import path in generated code for e.proto will look like `github.com/gen-go/a/c` which is not what I want. I want to have `github.com/a/c`.

**Comment by peter-edge** [comment]
This is setting up the `Mname=package` modifiers, which are go import paths. The `generate.go_options.import_path` `prototool.yaml` option defines the go import path to the `prototool.yaml` file, so for example if you have a go import path to a repository `github.com/foo/bar` and inside it you have `proto/prototool.yaml`, the value of `generate.go_options.import_path` will be `github.com/foo/bar/proto`. We then provide the option `generate.plugins.output`, for example https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml#L100, that says where the files will be located relative to the `prototool.yaml` file. So, the go import path of all together is `generate.go_options.import_path + generate.plugins.output + rel_path`.

In your example above, `github.com` is almost for sure not a correct value for `generate.go_options.import_path`. Likely, the value should be `github.com/team/repo/path/to/prototool_yaml_dir`. Please see the examples both in this repository and around GitHub (search for files named `prototool.yaml`).

This behavior is v1.0 and won't change, our apologies.

**Comment by peter-edge** [comment]
Here's a good example https://github.com/uber/prototool/blob/dev/example/idl/uber/prototool.yaml#L18

**Comment by peter-edge** [comment]
In your example above, you actually would want `github.com/gen-go/a/c`, as that would be the go import path if your repo was `github.com` (it is actually `github.com/team/repo`, see above), and the relative path inside the repo would be `gen-go`, so you would i.e. `go get github.com/gen-go/a/c`. Hope that helps!

**Comment by lidalei** [comment]
Thx a lot for your explanation. The thing is that `a` is the team name and `c` is the repo name.

The problem itself arises when generating Python3 code using prototool. And the Python root package is a/c. Assume there is another proto a/c/d/g.proto which imports a/c/d/h.proto. To make the import path correct in a/c/d/g_pb2.py code, I have to put all protos under a/c and set the import path `import a/c/d/h.proto`.

The problem is also stated in https://github.com/protocolbuffers/protobuf/issues/1491.

**Comment by peter-edge** [comment]
The code you referenced though only affects Golang plugins, i.e. plugins of type go or gogo. Can you explain how the above is affecting you with Python? If there’s a specific bug with Python generation, feel free to file a new bug, but please file the Issue Guidelines (which are copied into the issue description when you file an issue) and provide specific steps to reproduce (or we have to close it - we don’t mean to be impersonal but we have to be able to fix the actual bugs).

**Comment by lidalei** [comment]
This project (https://github.com/lidalei/protobuf/) shows how the problem looks like in generated Python code. The import statement `from response import response_type_pb2 as response_dot_response__type__pb2` in protobuf-gen-python/response/response_pb2.py does not work in Python3. It does not make use of the package directive `package dalei.protobuf.response;` while making use of the directory structure. It should be `from dalei.protobuf.response` if I want to pack it into dalei.protobuf. However, the generated PHP / Java code does respect the directive.

Thx a lot for your quick response and sorry for later reply.

**Comment by peter-edge** [comment]
We need specific, reproducible steps. If you can outline them in a new issue as the Issue Guidelines say, then we can take a look.

**Comment by lidalei** [comment]
Thx a lot. I'd say it not the problem of prototool but protoc. The best place is to solve it is protoc. Thx again and have a nice day!

**Comment by peter-edge** [comment]
You too! :-)
