### ISSUE TITLE
Support unix sockets

### ISSUE THREAD

**Issue by APTy** [uber/prototool#241]
## command I ran
```
prototool grpc myservice.proto \
  --address unix:///tmp/myservice.sock \
  --method myservice.FooService/DoFoo\
  --data '{"some": "data"}'
```

## what I expected to see
a successful response

## what I saw instead
```
dial tcp: address tcp////tmp/myservice.sock: unknown port
```

## discussion
the `--address` flag assumes a TCP address, but it'd be nice if a user can supply a `unix:///` prefix to allow for gRPC over unix socket

**Comment by amckinney** [comment]
Thanks for the issue @APTy! We'll take this into consideration and get back to you shortly.
