### ISSUE TITLE
Add lint option reference with rationale

### ISSUE THREAD

**Issue by johanbrandhorst** [uber/prototool#25]
Some of the lint options imply some sort of technical limitation, for example `MESSAGE_FIELDS_NOT_FLOATS`. I think the package should define a reference for the lint options and a rationale for each option so the user can make an informed decision about which ones to include.

**Comment by peter-edge** [comment]
I still don't understand what you're concretely proposing. If you can give me an example that would be great. The linter to disallow floats is not enabled by default, there's reasons for it and reasons against but that is outside the scope of this issue.

**Comment by peter-edge** [comment]
If you want to pursue this that's fine, let me know, otherwise I may close as "wontfix". I'm happy to take PRs though!

**Comment by johanbrandhorst** [comment]
Nice, I missed the style guide clearly, that's basically what I was looking for. Thanks!

**Comment by peter-edge** [comment]
No problem!
