### ISSUE TITLE
Formatting nested options produces code that emicklei/proto cannot parse

### ISSUE THREAD

**Issue by johanbrandhorst** [uber/prototool#27]
When the formatter processes the following file:

```protobuf
syntax = "proto3";

import "google/api/annotations.proto";

service Test {
    rpc Test(Void) returns (Void) {
        option (google.api.http) = {
            get: "/api/v1/test"
            additional_bindings {
                post: "/api/v1/test"
                body: "*"
            }
        };
    }
}

message Void {}
```
It produces the following:
```protobuf
syntax = "proto3";

import "google/api/annotations.proto";

service Test {
	rpc Test(Void) returns (Void) {
		option (google.api.http) = {
			get: "/api/v1/test"
			additional_bindings.post: "/api/v1/test"
			additional_bindings.body: "*"
		};
	}
}

message Void {}
```

This output is not parsable by `emicklei/proto` at the moment (see https://github.com/emicklei/proto/issues/80).

The options as I see it:
1. Change formatter to output the same code as in sample 1 above.
2. Wait for https://github.com/emicklei/proto/issues/80 to be fixed.
3. Replace `emicklei/proto` with something else (see #1).

**Comment by peter-edge** [comment]
Thanks for the detailed issue, I appreciate it. Will dig into this soon.

**Comment by emicklei** [comment]
We could revisit the choice to flatten the selector path into a dotted name. https://github.com/emicklei/proto/blob/master/option.go#L259. The alternative design will need to have a matching structure, e.g. nestable map of NamedLiteral.

**Comment by peter-edge** [comment]
This should be fixed now. I will do a new release soon, but this is fixed on dev.
