### ISSUE TITLE
Consider using clang-format for Protobuf formatting

### ISSUE THREAD

**Issue by isaachier** [uber/prototool#30]
Instead of writing your own Protobuf formatter, why not use the popular [clang-format](https://clang.llvm.org/docs/ClangFormat.html) tool which already supports Protobuf files?

**Comment by peter-edge** [comment]
Hey,

Thanks for the tip, I hadn't actually seen that before! It looks like a good tool, but our goals here are different. Prototool is meant to be a one-stop shop, as well as be a point for editor integration. While we could have a dependency on clang-format, it would be a non-Golang dependency and would not be in line with what we're trying to do here. It's better for us in the long term to have Prototool do exactly what we want for formatting than rely on another tool just for formatting.

**Comment by peter-edge** [comment]
Sure, we can try to match their formatting before v1.0, it is better to have one format for Protobuf than many formats.
