### ISSUE TITLE
Allow Java Packages with tld prefixes other than COM

### ISSUE THREAD

**Issue by dackroyd** [uber/prototool#324]
We've just started using prototool on a new project, and trying to adopt the `uber2` linting rules. We're running into a violation on the `FILE_OPTIONS_EQUAL_JAVA_PACKAGE_COM_PREFIX` rule, because our reverse dns is `au.com.<company>`, not `com.<company>`. I imagine that this would be a fairly common case for non-US based/non-global companies.

Ideally we'd like to be able to use the `uber2` ruleset without any rule exceptions, but mandating that Java packages start with `com` requires this rule to be disabled. If other tlds were supported, or the package prefix was overridable, this would allow the `uber2` ruleset to be used without exceptions.

I'm uncertain whether keeping the ability to use protos defined by other parties with different tlds would be required if overriding the package prefix.

**Comment by peter-edge** [comment]
Preliminary idea is to have a new `FILE_OPTIONS_EQUAL_JAVA_PACKAGE_PREFIX` linter and replacing  `FILE_OPTIONS_EQUAL_JAVA_PACKAGE_COM_PREFIX` with this linter for the `uber2` lint group. This linter would default to `com` being the prefix (so behavior is the same as it is now), however the configuration file would have a new option:

```yaml
lint:
  java_package_prefix: au.com
```

That would allow this to be configurable.

I am also reviewing the `uber2` lint set right now, and there will be a couple changes/removals, namely the `google.api.http` linter will go away (I don't think this should be part of the default rule set, rather it should be an add-on if desired).

**Comment by peter-edge** [comment]
Fixed on dev
