### ISSUE TITLE
Specify option for protoc plugin

### ISSUE THREAD

**Issue by JonasVautherin** [uber/prototool#329]
Say I create my own protoc plugin, `protoc-gen-custom`, and I want to pass an argument to it. In command line, it could look like this:

    protoc --plugin=protoc-gen-custom=my_plugin.py --custom_out=. --custom_opt=your_options

How can I specify the `--custom_opt` options using prototool?

Looking at the configuration, I see some [flags](https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml#L119) for plugins, but that's undocumented, and it doesn't sound like "options".

**Comment by peter-edge** [comment]
You can do this with `flags` - it is  documented, we link to this from the README.md https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml#L119

Maybe in the future we could revisit this and call it `opt`, but that would be a breaking change for v1, and we don't intend on doing a v2 for a long time.

**Comment by Arttii** [comment]
It is still unclear to me how to use thie flags. for example when trying to something like
`
     - name: docs
      path: protoc-gen-doc
      flags: doc_opt=html
      output: ../gen/docs/
`
the actual command prototool runs is
```
{"command": "/home/arti/.cache/prototool/Linux/x86_64/protobuf/3.6.1/bin/protoc -I protovendor/github.com/grpc-ecosystem/grpc-gateway -I protovendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis -I /home/arti/.cache/prototool/Linux/x86_64/protobuf/3.6.1/include -I protoproto --docs_out=doc_opt=html,:protogen/docs --plugin=protoc-gen-docs=/opt/tools/protoc-gen-doc protoprotoservice/service.proto"}
```
so it seems to just append flags to `docs_out`? This behavior is quite confusing, or I am just misunderstanding something.
