### ISSUE TITLE
feature request: vscode integration

### ISSUE THREAD

**Issue by jackielii** [uber/prototool#354]
VSCode plugin would be great!

**Comment by peter-edge** [comment]
Hey, yep thanks for the request - if you have an effort to build VSCode integration or know of one, that'd be great. We've thought about it before but I don't think it's something we're going to build ourselves anytime soon. Please do let me know if something comes up.

I'm going to close this as "wontfix" but don't think that means we're unsupportive - I'm trying to get us to Inbox Zero (which reminds me to clean up some other issues)
