### ISSUE TITLE
windows binary

### ISSUE THREAD

**Issue by jorgheymans** [uber/prototool#36]
Any chance to produce a windows binary as well ?

**Comment by peter-edge** [comment]
Duplicate of https://github.com/uber/prototool/issues/9, there’s some work to do first.

**Comment by jorgheymans** [comment]
thanks, i had seen that issue but did not realize it's aiming for the same thing

**Comment by peter-edge** [comment]
@jorgheymans can you check out the `windows` branch #177 and see if it works?

**Comment by jorgheymans** [comment]
@peter-edge just got back from holidays, is there something to test still ?

**Comment by peter-edge** [comment]
If you check out the `windows` branch and do `make install`, you can see if it works, and let us know in #9 what the issues are. Alternatively, you can just keep on working on the `windows` branch in a fork to make it work including with AppVeyor, and send us a PR :-)
