### ISSUE TITLE
escaped double-quotes break formatter

### ISSUE THREAD

**Issue by utrack** [uber/prototool#374]
Hi,

I've got an option in my protofile that looks like this:
```
message GetVariantBySKURequest {
  repeated int64 sku = 1 [
    (gogoproto.customname) = "SKU",
    (gogoproto.moretags) = "validate:\"required,dive,gt=0\""
  ];
}
```
After running `prototool all` the file is modified:
```
message GetVariantBySKURequest {
  repeated int64 sku = 1 [
    (gogoproto.customname) = "SKU",
    (gogoproto.moretags) = "validate:\"required,dive,gt=0\"
  ];
}
```
and files do not compile anymore.

It looks like the problem happens on `format` stage; any release since (at least) 1.0.0 to 1.3.0 are affected.

**Comment by utrack** [comment]
It seems that the bug comes from emicklei/proto.

**Comment by peter-edge** [comment]
OK so why haven't you filed a bug there?

**Comment by peter-edge** [comment]
I have submitted a fix at https://github.com/emicklei/proto/pull/104

**Comment by peter-edge** [comment]
Fixed on dev.
