### ISSUE TITLE
Dependency Management

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#4]
To get this off the ground, I did what I was used to and used [Glide](https://github.com/Masterminds/glide) as my dependency management tool. I wanted this to be go-gettable, so all this does is specify all necessary dependencies without versions, which are then checked into `vendor`. This has been fine for development, as Prototool does not expose any external API, and this makes installing Prototool as easy as `go get github.com/uber/prototool/cmd/prototool`.

However, we eventually will want to expose parts of Prototool as a Golang library, and this isn't a very efficient way to do this. We probably don't want to check in `vendor` in this case, and we want to get up to date by using [Dep](https://github.com/golang/dep). Installing Prototool will instead move to curl'ing binaries released to GitHub Releases.

Update: No longer checking in vendor, so probably all that is left here is to move from Glide to Dep.

**Comment by breerly** [comment]
Hey @peter-edge, I think we want to revisit moving prototool to dep.

It *looks* like Go is going to be throwing away dep in favor of vgo:

https://github.com/golang/go/issues/24301

Rather than switch to dep now, I say we hold back a bit to see what happens w/ vgo.

If Glide is that much of a pain, then we can just check in the vendor repo.

Regardless, Prototool is a binary, and so we shouldnt need this for v1.0.

cc @blampe @akshayjshah

**Comment by peter-edge** [comment]
Sounds fine to me.

**Comment by peter-edge** [comment]
Glide is fine, I used to check in vendor but especially pre-1.0 I don’t want to, it significantly increases the size of each commit that has a vendor update and makes making this a library harder.

**Comment by breerly** [comment]
Kk, using Glide for development seems fine for now!

**Comment by peter-edge** [comment]
Let’s keep this open for now to track this and to show users the rationale, I know others have a different opinion.

**Comment by johanbrandhorst** [comment]
I personally think it's a mistake to forsake `dep` in favor of waiting for `vgo`. `vgo` might make it into 1.11 as an optional extension, and adoption will probably take a while. Meanwhile, `dep` has been very well received by the community, is very similar to existing dependency management solutions (npm, yarn, cargo), will provide a clear upgrade path to the `vgo` system, and works _right now_. I get the point about this being released as a binary primarily, but if people want to use a stable version of this, they may well use `dep` to track the version, and I think we could benefit from having these definitions in this repo right now.

**Comment by blampe** [comment]
FWIW `vgo` already supports `dep` manifests out of the box, so I don't think we lose anything by doing this.

**Comment by peter-edge** [comment]
Closing this for now as there's nothing to do (and users can search for it, closed or not). I think Inbox Zero on Issues is always a good goal.
