### ISSUE TITLE
Format: enum values lose options > 1

### ISSUE THREAD

**Issue by cvanderschuere** [uber/prototool#400]
When more than one option is provided to an enum value, `prototool format` will strip out everything after the first one.

Example proto:
```protobuf
enum SomeEnum {
  SOME_ENUM_UNKNOWN = 0 [
    (option_1) = "a_value",
    (option_2) = "another_value"
  ];
}
```

From a quick look, this appears to be using [`EnumField.ValueOption`](https://godoc.org/github.com/emicklei/proto#EnumField) rather than `EnumField.Elements` in the format logic.

**Comment by peter-edge** [comment]
Thanks for reporting this. Will investigate.

**Comment by peter-edge** [comment]
Fixing this in #401 including adding this to the format testing.

**Comment by peter-edge** [comment]
This is fixed on dev. If using Go 1.12+, you can just do `go get github.com/uber/prototool/cmd/prototool@dev` or `go get github.com/uber/prototool/cmd/prototool@aae217351c684418bd56846dfef28f461f16e05d` to install from `dev` or to lock the install to the latest commit. If you want to install to a specific location and not affect your `go.mod`, you can do:

```bash
TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}" EXIT
cd "${TMP}"
GOBIN=/path/to/install/bin go get github.com/uber/prototool/cmd/prototool@aae217351c684418bd56846dfef28f461f16e05d
```

This is what we do basically at https://github.com/uber/prototool/blob/dev/Makefile#L43
