### ISSUE TITLE
prototool lint does not correctly output column

### ISSUE THREAD

**Issue by mattbailey** [uber/prototool#411]
The column is always either `1` or `2`:

```
❯ cat test.proto
syntax = "proto3";

package someproto;

option go_package = "throwlint";
option java_multiple_files = true;
option java_outer_classname = "pb";
option java_package = "pb";

~/tmp
❯ prototool lint test.proto
test.proto:5:1:Expected "someprotopb" for option "go_package" but was "throwlint".
test.proto:7:1:Expected "TestProto" for option "java_outer_classname" but was "pb".
test.proto:8:1:Expected "com.someproto" for option "java_package" but was "pb".
```

**Comment by peter-edge** [comment]
This is correct - the option starts at column 1, this is what the parser is referring to, not the value in the quotes. If you’d like to discuss this, open an issue on emicklei/proto (however in my opinion this should stay as-is).

**Comment by mattbailey** [comment]
That makes it pretty difficult to integrate with editors. IMO the column reported by the linter should indicate the thing the linter is suggesting you change. I'll take it to the other repo though...
