### ISSUE TITLE
Break check not working as expected

### ISSUE THREAD

**Issue by rappas1** [uber/prototool#412]
Break check not working as expected..

If I have a duplicate value and a name change in a file it is only showing duplicate error. Once I fix it then it is showing name change.

**Comment by peter-edge** [comment]
This does not meet the issue guidelines - if filing a bug, you must provide specific reproducible steps to recreate the issue. I haven’t seen the above problem in any testing we have done so I think this may be unrelated to Prototool.

If you have specific reproducible steps, feel free to re-file this issue.
