### ISSUE TITLE
Steps to install prototool on windows

### ISSUE THREAD

**Issue by rappas1** [uber/prototool#414]
Can we install prototool on windows operating system. Can you please share the steps(commands) to install on windows.

Thanks,
Rajesh

Thanks for filing an issue! We appreciate the input.

Before filing, a couple guidelines:

- If this is a question about Protobuf, do not file an issue here. Consult the
  Protobuf Language Guide at https://developers.google.com/protocol-buffers/docs/proto3
  or ask your question on the Protobuf Mailing List at https://groups.google.com/forum/#!forum/protobuf.
- If this is an issue with Protoc, do not file an issue here. File your issue
  on the Protobuf repository at https://github.com/protocolbuffers/protobuf.
- If this is a feature request, please provide a rough outline of the actual changes
  you'd like to see with as many specifics as you can provide.
- If this is a bug report, please provide specific steps to reproduce your issue.

Please do not @ individual maintainers in the description! We appreciate it.

If your issue doesn't meet the guidelines, we'll comment as such and close the issue - we don't
mean to be impersonal, but we have to reduce the support burden and cannot be supporting all
of Protobuf. If the issue is a feature request and we don't think it meets the guidelines,
don't feel like us closing the issue means we can't ever address it, unless we specifically
note that we won't be adding a given feature (in which case the issue should stay closed)
- provide more specifics and re-open the issue. If the issue is a bug report, unless we respond
that Prototool is working as intended, add steps to reproduce the issue and re-open the issue.

Again, thanks for your input, and we hope Prototool helps your development!

**Comment by peter-edge** [comment]
Windows is not supported. We are looking for help if someone wants Windows support. See #9 and #177.
