### ISSUE TITLE
Dockerfile protoc version update

### ISSUE THREAD

**Issue by YunLiaw** [uber/prototool#424]
Hi, 

I found that in [Dockerfile](https://github.com/uber/prototool/blob/v1.6.0/Dockerfile#L46) the version of protoc is still pin to `3.6.1`. I would like to know if it can be updated to 3.7.1 as the default.

Thanks!

**Comment by peter-edge** [comment]
Given how the Dockerfile currently installs it, it can’t until https://pkgs.alpinelinux.org/package/edge/main/x86_64/protobuf is updated. I’d like to keep this installation method as it is a prerequisite for gRPC and installing grpc from apk is much quicker than building from source.
