### ISSUE TITLE
Customizing plugins to be used for compiling for each .proto file

### ISSUE THREAD

**Issue by F21** [uber/prototool#434]
I have a fleet of microservices, with each service contained within its own repository. I am looking to move all protobuf definitions from each service's repository into a centralized repository.

For most services, there are currently 2 types of protobuf definitions:
- A standard protobuf wire definition that is compiled without any plugins using the Go compiler.
- A GRPC definition that is compiled with the GRPC and protoc-gen-validate plugins using the Go compiler.

My current thinking is to store the .proto files under a folder for each service and generate the appropriate target for each language into a folder:
```
service1
   | events.proto
   | services.proto
   | go
      events.pb.go
      services.pb.go
   |ruby
      ...
service2
  | events.proto
  | services.proto
  | java
     ...
```

I am not sure if this is the best way to organize multiple languages/targets within a repo. However, the more pressing issue is that I want `event.proto` to be processed using just the Go compiler and `services.proto` to be processed with the GRPC and `protoc-gen-validate` plugins.

From my understanding of the `prototool.yml` configuration, all plugins defined will be used to process all .proto files. I think I can move `events.proto` and `services.proto` into their own subfolders and add a `prototool.yml` file to each folder. However, this seems to be quite tedious just to modify the plugins required for each `.proto` file. In addition, if there is some global setting such as linting that needs to be modified in the future, I'll need to make the change to all `prototool.yml` files. 

Ideally, I'd love to be able to annotate a list of plugins applicable within the .proto file itself for prototool to pick up. However, this might not be so straight forward as some plugins may not support the available targets/languages (for example, `protoc-gen-validate` currently does not support ruby).

**Comment by peter-edge** [comment]
See #350 - we can't accommodate this, our apologies.
