### ISSUE TITLE
config init command with --document flag produces invalid yaml file

### ISSUE THREAD

**Issue by kniels21** [uber/prototool#440]
Hi,
  Ive found a small issue around setting up a new `prototool.yaml` file using the `prototool config init` command with the `--document` option. It appears as though the the initial yaml file produced contains the `lint:` directive commented out with the `group: uber2` directive not commented out.

Executing the `prototool break check` command using this yaml file produces the following error:

`yaml: unmarshal errors:
  line 49: field group not found in type struct { AllowUnusedImports bool "json:\"allow_unused_imports,omitempty\" yaml:\"allow_unused_imports,omitempty\""; Version string "json:\"version,omitempty\" yaml:\"version,omitempty\""; Includes []string "json:\"includes,omitempty\" yaml:\"includes,omitempty\"" }`

Uncommenting `lint:` in the produced yaml file fixes the issue. If you can confirm this is a simple template fix and not intended behavior I can submit a PR to make this small fix.

Thank you

**Comment by peter-edge** [comment]
Thank you for pointing this out! Yes, this is an issue, however would you be OK if I fix it? The template file is very fragile regarding spaces, so it would be easier for me if I did it. If you really want, I can review a PR you put up, up to you.

**Comment by kniels21** [comment]
Yep sure no problem with you fixing it. Thank you for the quick response.

**Comment by peter-edge** [comment]
Fixed on the dev branch, this will go out in the next release. Thanks for this!
