### ISSUE TITLE
Managing imports in .proto files

### ISSUE THREAD

**Issue by lyonssp** [uber/prototool#444]
I have a project with protos in several different directory paths, but I want to generate all protos from a single `Makefile` at the root of my `GOPATH`.

The structure looks like this:
```
github.com/go/path
-- Makefile
-- foo/
---- bar/
------ bar.proto
------ prototool.yaml
-- baz/
---- qux/
------ qux.proto
------ prototool.yaml
```

bar.proto
```
syntax = "proto3";

package bar;

message Bar {
  string s = 1;
}
```

qux.proto
```
syntax = "proto3";

package protos;

import "github.com/go/path/foo/bar/bar.proto"

message Qux {
  Bar bar = 1;
}
```

I'm trying to generate Go stubs for `bar.proto`, but the import cannot be resolved when I do the following from my project root
```
docker run -v "$(pwd):/work"  uber/prototool:latest prototool generate bar/qux
```

What's the idiomatic way to make protos in one directory aware of types in another?

**Comment by peter-edge** [comment]
I believe you meant `docker run -v "$(pwd):/work" uber/prototool:latest prototool generate baz/qux`

Per the [File Discovery](https://github.com/uber/prototool/tree/dev/docs#file-discovery) section, Prototool automatically figures out imports across all directories for a single `prototool.yaml` configuration - see  https://github.com/uber/prototool/tree/dev/example. I don't think you should be using multiple `prototool.yaml` files here.

Per the File Discovery  and [Tips and Tricks](https://github.com/uber/prototool/tree/dev/docs#tips-and-tricks) sections, you should have your imports start from the directory your `prototool.yaml` file is in, so in general you would not import from what appears to be the start of the `GOPATH` (ie `github.com/go/path/foo/bar/bar.proto`). However, the overarching issue is that you're expecting Prototool to maintain imports across two logical sets controlled by separate `prototool.yaml` files, which is not a feature of Prototool.

You could do this in `baz/qux/prototool.yaml`:

```yaml
protoc:
  includes:
    - ../..
```

And then in qux.proto:

```proto
syntax = "proto3";

package protos;

import "foo/bar/bar.proto"

message Qux {
  Bar bar = 1;
}
```

But this isn't idiomatic - Prototool is really meant to manage one set of files.

**Comment by peter-edge** [comment]
Closing this as this isn't a fixable issue - this is just a matter of how Prototool works. Feel free to comment here if you have more questions, but my recommendation would be to pattern off the example.
