### ISSUE TITLE
Suggest using glibc when running protoc in alpine

### ISSUE THREAD

**Issue by F21** [uber/prototool#447]
I tried using protoc in Alpine with the `libc6-compat` package as suggested in the FAQ: https://github.com/uber/prototool/blob/dev/docs/faq.md#alpine-linux-issues.

Protoc always fails with `exit status 127`. I tried protoc 3.7.1 and 3.6.1. I was able to get it working after installing glibc: https://github.com/sgerrand/alpine-pkg-glibc

**Comment by peter-edge** [comment]
Thanks for the note! Can you tell me specifically what steps you ran?

**Comment by peter-edge** [comment]
I put up #449 to update the FAQ. Thank you so much for filing this!

**Comment by peter-edge** [comment]
Changed on dev, thanks!
