### ISSUE TITLE
lint with google will fail OBSOLETE_ prefix

### ISSUE THREAD

**Issue by amazingandyyy** [uber/prototool#450]
Hi we are using `google` style guide for our lint checking,

currently we follow Google's docs to add `OBSOLETE_ ` to indicate a fields is removed, this pattern is showed in the **Updating A Message Type** session in the official docs: https://developers.google.com/protocol-buffers/docs/proto3

But with this practices, it will fail the lint check for multiple rules e.g. 
to remove the enum we did 
```
enum OBSOLETE_CartItemType {
}
```
it will fail the rule of **all enum names are CamelCase**

**Comment by peter-edge** [comment]
The Google style guide is at https://developers.google.com/protocol-buffers/docs/style

The above will fail as it violates it. Per the Prototool documentation, if you’d like to ignore a specific lint rule, you can add it to lint.rules.remove in your prototool.yaml configuration file.

This is working as intended. The above is also a breaking change, which would fail prototool break check as well.
