### ISSUE TITLE
Feature Request: Custom Defined Templates 

### ISSUE THREAD

**Issue by jpreese** [uber/prototool#452]
Looking into leveraging prototool for our protocol buffer needs, as it checks a lot of boxes for us. Though after a bit of playing around and digging through the source, it doesn't look like its possible to configure the template or much of the values that are used for `prototool create`. 

If I am missing functionality thats already supported by the tool and/or I'm missing something, please let me know.

Case 1: Removing the Java package naming in the `.proto` file as we do not plan on leveraging Java. It seems the create tool chooses from two data templates, both of which include Java. It's not the end of the world to include these for future proofing, but would still be nice.

Case 2: Custom defined go_packages. For example, I do not see a way to create a `.proto` file that has a protocol buffer package name of X, but a go_option package name of Y. In other words, I would want my protocol buffer package to be `package service`, but my go_option to be `go_option = "myurl.com/api/services/servicename"`

**Comment by smaye81** [comment]
This is a good request but I don’t think we have the budget/resources to do this properly…there’s a lot involved to expose this in a manner we would be OK with via config, and given the marginal benefits, we probably won't implement at this time.  There's a lot of cross-integration that would be affected, such as the `create` and `lint` functionality.  

Thanks for filing though.  Worth considering for the future.
