### ISSUE TITLE
Lint task returns 255 error code when custom remove rules are used

### ISSUE THREAD

**Issue by kniels21** [uber/prototool#453]
Hi,
  I am using the `prototool` linter task to validate some auto created protobuf schema files. Im finding that if i specify custom linter rules (mostly removes) and check the error status on a successful lint task run, I am receiving a `255` code with an empty output message.  It seems as though the successful lint task should return `0`. 

Thank you for your time.

**Comment by jpreese** [comment]
Could you provide the `.proto` file that you're trying to validate as well as the `prototool.yaml` ?

I would agree, what you have described should return an error code of `0`.

**Comment by smaye81** [comment]
Please re-file if you have reproduction steps per the issue guidelines.
