### ISSUE TITLE
Break command and Alpha packages

### ISSUE THREAD

**Issue by jpreese** [uber/prototool#455]
I'm not seeing any support for `alpha` packages with the `break` command, only `beta`. If this is intended, it may be valuable to add into the documentation why `alpha` packages are not considered. For example, In Uber's protocol buffer journey, did you guys feel that alpha packages did not provide value?

I personally would've set it up so that `alpha` changes are allowed to break, because its in its initial development phase and you're trying to get feedback. Things get added, things get removed, unstable. Right now, alpha packages cannot break.

Then a `beta` package would be introduced where things could NOT break. The API is pretty much stable at this point, but there are maybe a couple things to iron out before an official release.

The above is a drastic change to how the tooling works, so I don't expect that to change, but just wanted to give me insights. Though I do think minimally, `alpha` should also be allowed to break for companies who use `alpha` packages.

I understand there's no clear cut answer and a lot of it weighs on how the company wants to operate, but given how the Style Guide talks about how it was created out of trial and error, and was found to be the best configuration. I think there's value in carrying that over to the `break` tool and why `alpha` is not included.

**Comment by smaye81** [comment]
We use `beta` as the only designation for ‘allowed to break’, not `alpha`.  It’s really just a design decision.  There's been no need for any more granularity for that.  Having a `beta` environment for breaking changes followed by an official blessed version has served us well so far and we don’t see ourselves changing it.
