### ISSUE TITLE
Feature request: Lint message field names camelCase

### ISSUE THREAD

**Issue by maxsommer** [uber/prototool#462]
Hi everyone! I'd be very happy to have the option to enforce camelCase on message field names. As of now it seems the only rules allowed regarding message field names are enforcement of
- filename
- filepath
- lowercase
- lower snake case
- no descriptor

Since other entities like message themselves and enums e.g. have the option to enforce camelCase I feel we'd need this at the very least to be consistent.

If third party contributions are desired I'd happily help out with some guidance which parts of the system need a touch then.

---

EDIT: I've already cloned the repository introducing a new lint file building up on the existing rules for camelCase and registering it to AllLlinters in `lint.go` where I would suspect it all to come together. As a go noob I'm however failing at actually running and testing my code. I've read the contributions guide and tried reading through some go guides. Any hints to how I can actually run prototool with my modified source code? (Yes, this is embarrassing for me as a professional developer😳)

**Comment by smaye81** [comment]
Message names should be lower snake case, not just per our style guide but per [Google’s official style guide](https://developers.google.com/protocol-buffers/docs/style).  We don't intend to support every permutation for style unfortunately.

Re: running locally, have you simply just tried `go install` with your modified source code?
