### ISSUE TITLE
protoc returned a line we do not understand

### ISSUE THREAD

**Issue by ZebingZong** [uber/prototool#463]
Reproduce steps:
1) idl fetch code.uber.internal/mobile/screenflow-api
2) make clean
3) make

Errors:
2019-06-06T12:10:03.006-0700	WARN	protoc returned a line we do not understand, please file this as an issue at https://github.com/uber/prototool/issues/new	{"protocLine": "2019/06/06 12:10:02 protoc-gen-gogo: error:inconsistent package names: triggerspb entitiespb"}
<input>:1:1:2019/06/06 12:10:02 protoc-gen-gogo: error:inconsistent package names: triggerspb entitiespb
<input>:1:1:protoc-gen-gogoslick failed with status code 1.
idl/code.uber.internal/lm/fievel/marketplace/fulfillment/queries/transport_provider.proto:1:1:Import "lm/fievel/marketplace/fulfillment/entities/transport_provider.proto" was not used.
idl/code.uber.internal/lm/fievel/marketplace/fulfillment/queries/transport_provider.proto:20:3:"uber.marketplace.fulfillment.entities.TransportProviderEntityData" is not defined.
idl/code.uber.internal/lm/fievel/marketplace/fulfillment/triggers/transport_provider_user.proto:1:1:Import "lm/fievel/marketplace/fulfillment/entities/transport_provider.proto" was not used.
idl/code.uber.internal/lm/fievel/marketplace/fulfillment/triggers/transport_provider_user.proto:26:3:"uber.marketplace.fulfillment.entities.TransportProviderEntityData" is not defined.
idl/code.uber.internal/lm/fievel/marketplace/fulfillment/triggers/transport_provider_user.proto:34:3:"uber.marketplace.fulfillment.entities.TransportProviderEntityData" is not defined.
make: *** [.tmp/.faux.protoc] Error 1

**Comment by smaye81** [comment]
Just to verify, are you specifying a Go package in your protos?   See this issue and let me know if this helps at all.

https://github.com/golang/protobuf/issues/159#issuecomment-203038389

**Comment by smaye81** [comment]
Also please do not specify internal naming in public issues :)
