### ISSUE TITLE
no check for correct directory structure results in python code breaking changes

### ISSUE THREAD

**Issue by Inilien** [uber/prototool#465]
Right now it is possible to put proto files in a directory structure which does not match package sub-names. While the style-guide [expects](https://github.com/uber/prototool/tree/dev/style#directory-structure) that this should never happen.

<details>
  <summary>Click to expand for code to reproduce</summary>

`$ tree .`
```
.
├── prototool.yaml
└── test
    └── bar
        └── test.proto

2 directories, 3 files
```
`$ cat prototool.yaml `
```
protoc:
  version: 3.7.1
lint:
  group: uber2
generate:
  plugins:
    - name: python
      output: '../gen/python/'
```
`$ cat ./test/bar/test.proto `
```
syntax = "proto3";

package test.foo.bar.v1;

option csharp_namespace = "Test.Foo.Bar.V1";
option go_package = "barv1";
option java_multiple_files = true;
option java_outer_classname = "TestProto";
option java_package = "com.test.foo.bar.v1";
option objc_class_prefix = "TFB";
option php_namespace = "Test\\Foo\\Bar\\V1";

// Test message.
message Test {
  string test = 1;
}
```
`$ prototool all .` - executes without any errors
</details>

------

Meanwhile, if my understanding of protobuf is correct, in the case of the python generated stubs, changing filepath of proto files results in new python packages. So the old code would not be working with the new stubs.

<details>
  <summary>Click to expand for code to reproduce</summary>

 For example, given the same files: 
`test/proto $ tree .`
```
.
├── prototool.yaml
└── test
    └── bar
        └── test.proto
```
`test/gen/python $ python`
```
Python 3.7.3 (default, Apr 16 2019, 16:31:11) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import test.bar.test_pb2
>>> import test.foo.bar.test_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'test.foo'
```
Full Pyhton package name is determined by file structure so right now it is `test.bar.test_pb2`. The package name analouge cannot be imported since there are no such module.  

Save proto definition to check for breaking changes later:
`test/proto $ prototool break descriptor-set ./test -o ./descriptor_set`
`test/proto $ tree`
```
.
├── descriptor_set
├── prototool.yaml
└── test
    └── bar
        └── test.proto
```
Also delete old Python stubs
`test/gen/python $ rm -rf ./*`
`test/gen/python $ tree`
```
.

0 directories, 0 files
```

Now, let's assume later someone decides to move `test.proto` into its proper location: 
`test/proto $ mkdir ./test/foo`
`test/proto $ mv ./test/bar ./test/foo/`
`test/proto $ tree .`
```
.
├── descriptor_set
├── prototool.yaml
└── test
    └── foo
        └── bar
            └── test.proto
```
Prototool works without any errors
`test/proto $ prototool all .`
There are also no breaking changes 
`test/proto $ prototool break check ./test -f ./descriptor_set`

But the old python code is not working anymore:
`test/gen/python $ touch ./test/__init__.py`
`test/gen/python $ tree`
```
.
└── test
    ├── foo
    │   └── bar
    │       └── test_pb2.py
    └── __init__.py

3 directories, 2 files
```
`test/gen/python $ python`
```
Python 3.7.3 (default, Apr 16 2019, 16:31:11) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test.bar.test_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'test.bar'
>>> import test.foo.bar.test_pb2
>>> 
```
</details>

----

So if the directory structure would be forced to match package sub-names (as style guide requires) than this situation would be impossible since `prototool all .` would return an error.  
Or if at least a check in `prototool break` would be added to forbid the moving of proto files into another filepaths - then there would be no python related breaking changes as well (but the style guide option seems more preferable to me)

**Comment by Inilien** [comment]
Turns out it is also possible to define the same message in the same package as long as directory structures for these proto files are different.
<details>
<summary>click for code to reproduce</summary>

`$ tree`
```
.
├── prototool.yaml
└── test
    └── foo
        ├── bar
        │   └── test.proto
        └── test2.proto

3 directories, 3 files
```
`$ cat ./test/foo/bar/test.proto `
```
syntax = "proto3";

package test.foo.bar.v1;

option csharp_namespace = "Test.Foo.Bar.V1";
option go_package = "barv1";
option java_multiple_files = true;
option java_outer_classname = "TestProto";
option java_package = "com.test.foo.bar.v1";
option objc_class_prefix = "TFB";
option php_namespace = "Test\\Foo\\Bar\\V1";

// Test message.
message Test {
  string test = 1;
}
```
`$ cat ./test/foo/test2.proto`
```                                                                     
syntax = "proto3";

package test.foo.bar.v1;

option csharp_namespace = "Test.Foo.Bar.V1";
option go_package = "barv1";
option java_multiple_files = true;
option java_outer_classname = "Test2Proto";
option java_package = "com.test.foo.bar.v1";
option objc_class_prefix = "TFB";
option php_namespace = "Test\\Foo\\Bar\\V1";

// Test message.
message Test {
  string test = 1;
}
```
`$ prototool all .` - no errors
</details>

**Comment by smaye81** [comment]
This is a good idea for a linter but outside the scope of prototool unfortunately.
