### ISSUE TITLE
unclear intention of allowing UNSET enum value != 1

### ISSUE THREAD

**Issue by Inilien** [uber/prototool#467]
In your [style guide](https://github.com/uber/prototool/blame/dev/style/README.md#L652) it is said that the `UNSET` Enum Value should be 1.  
But there are no error for assigning it to any other value (except for 0 of course).  
I was wandering if it is intentional (in which case it would be nice to have this mentioned in style guide to be sure that such restriction would not appear in the future) or if it is actually possible that in future some check might be added to lint rules which would prevent compilation of proto files with `UNSET` enum value not equal to 1?  
In the later case I would suggest to always require to define `UNSET` value in each enum but with `deprecated` option in cases when it is not needed right away (in order to prevent breaking changes in future)

**Comment by smaye81** [comment]
This is not a linter we’ll add unfortunately
