### ISSUE TITLE
Support configurability in break check

### ISSUE THREAD

**Issue by abhishekrb19** [uber/prototool#468]
Prototool breaking change detector is a great tool for detecting backward incompatibility of protobuf definitions.  Today, the `break check`, unlike `lint`, is not configurable and hence restricts usage of the feature. Found a comment in the codebase, wondering if there's any other good reason to not make it configurable: https://github.com/uber/prototool/blob/dev/internal/breaking/breaking.go#L33

**Proposal to make it configurable:**
- If a field/message is deleted, there has to be a corresponding `reserved`  marking the field numbers that are deleted (https://developers.google.com/protocol-buffers/docs/proto3#reserved) - so the field numbers are not accidentally used in the future which will break backward compatibility.
- Renaming of fields is not a backward incompatible change and we should have the ability to whitelist (`MESSAGE_ONEOFS_FIELDS_NOT_REMOVED`) from a schema's point of view. In fact, the documentation recommends prefixing/renaming obsolete fields if not removed - https://developers.google.com/protocol-buffers/docs/proto3#updating 
-  I understand some of the rules can and never should be violated and we could categorize the existing rules into a group and do this. For the above reasons, selectively configuring breaking check rules would be useful.

If it is deemed this proposal is legitimate, I'm happy to do this work.

**Comment by smaye81** [comment]
Unfortunately, this is outside the scope of prototool - we don’t allow configurability of what is considered a breaking change, we specify what we consider to be a breaking change and why in our [README.md](https://github.com/uber/prototool/blob/dev/docs/breaking.md). 

However, if you’d like a configurable breaking change detector, check out github.com/nilslice/protolock
