### ISSUE TITLE
prototool format does nothing if import missing

### ISSUE THREAD

**Issue by prestonvanloon** [uber/prototool#470]
I want to format my proto file, but the tool seems to do nothing at all if there is a missing import file. 

Why does the tool need this file to format it?

Additionally, I'm trying to format a single file and the tool is failing due to a sibling having the import error.

**Comment by smaye81** [comment]
Due to the implementation of `prototool` and the overall Protobuf ecosystem, `protoc` is the only reliable way to denote whether a file is in fact valid protobuf (see https://github.com/uber/prototool/issues/1).  We don’t intend to update this at this point unfortunately.

**Comment by prestonvanloon** [comment]
Please re-open this. Why is it the expected format that the tool does not format a file if an import is missing?

Imagine this:
```protobuf
syntax = "proto3";
package example;

import "something/that/doesnt/exist";

message      Example { 
 The string = 1
     Formatting string =   2;
Is string = 3;
                        bad string = 4;
}
```

Shouldn't prototool fix this formatting, even if the import doesn't exist?
