### ISSUE TITLE
v1.8.0 tag was moved?

### ISSUE THREAD

**Issue by AlCutter** [uber/prototool#472]
Howdy,

it looks a lot like you may have moved the `v1.8.0` tag on master?

This appears to be causing an issue for folks who are using the Google golang module proxy (in particular, [us](https://github.com/google/trillian) :)) as the proxy happened to see the version which was originally tagged, resulting in the following problem which will likely be biting others too:

```console
$ export GOPROXY=https://proxy.golang.org
$ export GO111MODULES=on
$ go clean -modcache
$ go mod download github.com/uber/prototool@v1.8.0
----8<---snip---8<----
verifying github.com/uber/prototool@v1.8.0: checksum mismatch
downloaded: h1:goRKXNdLz420vcXR5udSff/RUKXcL8B57FATe0u8uSs=
go.sum:     h1:AByDUuTG5nphja3+APWR04YPUjp7Ac0fZp/St1RKHlY=
```

The [Semver spec](https://semver.org/) (which `go mod` uses to reason about package versions) [says](https://semver.org/#spec-item-3) _"once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version."_, so I _think_ that the easiest way to sort this might be to issue a `v1.8.1` tag or similar?

**Comment by smaye81** [comment]
Yeah, apologies.  We did move the 1.8 tag because there were some issues with the release.  My guess is you updated in that interim.  I can certainly issue a `v1.8.1` tag to remedy this.  Just out of curiosity, though, is it possible to regenerate your `go.sum`?  There should be no major changes in those two checksums that should cause any issues.

If that's not doable for you, I can push up a 1.8.1 tag instead.

**Comment by AlCutter** [comment]
Hi Steve,

Yes, unfortunately the go module proxy we're using (https://proxy.golang.org) has already seen the `v1.8.0` tag, associated it with the first mod checksum, and it won't update it to the new one due to the semver rules. If I check-in a `go.sum` with that original checksum it'll work for folks using _that_ proxy, but it'll fail for everyone else (and vice-versa).

If you wouldn't mind making a `v1.8.1` that'd be cool.

Cheers,
Al.

**Comment by smaye81** [comment]
I pushed up a v1.8.1 tag, which tags the same v1.8.0 commit.  Let me know if that helps.

**Comment by smaye81** [comment]
Please re-open if there’s still issues, closing for now.  Sorry for any inconvenience.
