### ISSUE TITLE
Google style guide: enum UNSPECIFIED suffix rule.

### ISSUE THREAD

**Issue by jden123** [uber/prototool#480]
[Google style guide](https://developers.google.com/protocol-buffers/docs/style) says 

> The zero value enum should have the suffix UNSPECIFIED.

Are we able to setup this validation? I cannot find such rules. Should we add it? 

Can we add strict google group to follow all the rules described in the style guide?

**Comment by smaye81** [comment]
We actually vary slightly in the treatment of zero-value enums, as addressed in the [style guide](https://github.com/uber/prototool/tree/dev/style#enums).

There is a semantic difference between 'unset' and 'invalid'.  Having a single value of `UNSPECIFIED` as the default could be confusing in some instances (again see style guide).

**Comment by jden123** [comment]
Thank you. I saw and understand that. But if we have `google` group should we support all the rules?

I'm looking for a good style guide. Do you suggest to use `uber2`?

**Comment by smaye81** [comment]
Yeah I see your point.  The `google` group should probably support all rules in their style guide.  Probably a good task for the future.

Our `uber2` style guide is pretty comprehensive, so I definitely endorse it.  It's prescriptive, so if you don't want that sort of thing, it might not be for you, but I would recommend it.

**Comment by jden123** [comment]
Thank you!
