### ISSUE TITLE
Add ability to remove certain linters just for one message

### ISSUE THREAD

**Issue by mikhailkolesnik** [uber/prototool#490]
Consider this situation:
There is a legacy API that we would like to define using protobuf and use prototool to generate code and such.

This API has some properties that break existing linter. For example enum values with values of `0` which are not `INVALID` enum values.

It would  make sense to disable `ENUM_ZERO_VALUES_INVALID` linter just for that enum and keep it enabled for every other including the ones that are added to that package as expansion.

Currently it seems the only way to remove linter is a global setting for the whole package.

**Comment by smaye81** [comment]
I'm not sure that is super helpful.  The purpose of the linters would be for universal consistency and allowing them to be disabled for certain messages/files would defeat that purpose.
