### ISSUE TITLE
Allow passing plugin parameters via --<lang>_opt

### ISSUE THREAD

**Issue by rabbitinspace** [uber/prototool#494]
The problem with passing plugin parameters via `--<lang>_out` is if any of them will contain `:` symbol `protoc` will consider everything that comes after that symbol as path to output directory.

For example, I have a plugin entry in `prototool.yaml`:
```
- name: rust
  output: ../satelit-cli/src/proto
  flags: grpc,no-flat-modules,extern-path=.uuid.UUID=::uuid::Uuid
  path: plugins/bin/protoc-gen-rust
```

The following `--rust_out` parameter will be generated when `prototool generate` is invoked:
```
 --rust_out=grpc,no-flat-modules,extern-path=.uuid.UUID=::uuid::Uuid:/.../satelit-cli/src/proto 
``` 

As a result, `protoc` will consider `grpc,no-flat-modules,extern-path=.uuid.UUID=` part as plugin parameters and `:uuid::Uuid:/.../satelit-cli/src/proto` part as output path which is incorrect.

I believe that the correct way of passing such parameters is via `--rust_opt`:
```
--rust_opt=grpc,no-flat-modules,extern-path=.uuid.UUID=::uuid::Uuid --rust_out=/.../satelit-cli/src/proto
```

But there's no way to ask `prototool` to do that. 

([the fix is straightforward](https://github.com/satelit-project/prototool/commit/bec24d2e1acb072a049476ebfaf203ae4b07dbc0) but I'm not sure if you'll consider the issue as worth fixing)

**Comment by maarek** [comment]
Was there a reason this never got updated?

**Comment by rabbitinspace** [comment]
I suppose that's because `prototool` is not actively maintained anymore

**Comment by smaye81** [comment]
It is maintained, albeit not as actively as I would like.  However, this is still an active product / repo.   There was definitely a down period in maintenance in late 2019, which I'm assuming is why the issue was closed?

**Comment by rabbitinspace** [comment]
Yeah and I closed it as soon I saw a note in the readme about Buf.
Happy to re-open it if you think it worth fixing.
