### ISSUE TITLE
Unable to go get for go1.13

### ISSUE THREAD

**Issue by ninedraft** [uber/prototool#496]
**Go version:** 1.13

**Description:**
go get unable to install prototool (v1.8.1) because of malformed dependency pseudoversion

**How to reproduce:**
```bash
go get github.com/uber/prototool/cmd/prototool@v1.8.1
```

**Output:**
```
get "google.golang.org/genproto": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at //google.golang.org/genproto?go-get=1
go get: github.com/uber/prototool@v1.8.1 requires
	github.com/jhump/protoreflect@v1.4.1 requires
	google.golang.org/genproto@v0.0.0-20170818100345-ee236bd376b0: invalid pseudo-version: does not match version-control timestamp (2017-08-18T01:03:45Z)
```

**Possible solution:** update [github.com/jhump/protoreflect](github.com/jhump/protoreflect) `v1.4.1` to `v1.5.0`

**Comment by smaye81** [comment]
This should be fixed by https://github.com/uber/prototool/pull/495.  Can you test it from the dev branch and verify?  I will cut a release to get this officially versioned.

**Comment by andrehp** [comment]
When will the version with this fix be versioned?

**Comment by smaye81** [comment]
Apologies.  I plan to do this tonight.

**Comment by smaye81** [comment]
Having some dependency issues with the upgrade to Go 1.13.  There are some unit tests failing that I will need to look into.  In the meantime, you can always just `go get` the dev branch as illustrated here:

**Comment by awishformore** [comment]
It would be neat if this fix would be released soon.

**Comment by smaye81** [comment]
OK, sincerely apologize for the delay.  I was finally able to devote some time to fixing the myriad dependency issues.  

https://github.com/uber/prototool/pull/513

**Comment by hit9** [comment]
When a tag will be released? Waiting for new release..

**Comment by smaye81** [comment]
This should now be released.  v1.9.0 will include the updated dependencies.

**Comment by smaye81** [comment]
Going to close this issue.  If a problem still persists, please reopen.
