### ISSUE TITLE
Repeated fields rule

### ISSUE THREAD

**Issue by jden123** [uber/prototool#509]
Google style guide suggests using pluralized names for [repeated fields](https://developers.google.com/protocol-buffers/docs/style#repeated-fields) (Ex: `keys` instead of `key`). 

Is it possible to setup this validation? I think this rule is useful.

**Comment by smaye81** [comment]
We've actually wanted to make the current `google` lint group be more in line with Google's style guide.  Created https://github.com/uber/prototool/issues/514 to track this as a bigger effort.

**Comment by smaye81** [comment]
After some thought, also, I realized that it is super difficult to determine a plural form of a word based on no context and no singular form to compare it with.  I don't see us adding this lint rule any time soon.  Apologies.
