### ISSUE TITLE
Cannot specify version v3.10.0-rc1 in prototool.yaml

### ISSUE THREAD

**Issue by alisonbelow** [uber/prototool#512]
Prototool is unable to support version 3.10.0-rc1 specified in prototool.yaml file.

If the `prototool.yaml` file looks like:
```yaml
protoc:
  version: 3.10.0-rc1
```
then the URL https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0-rc1/protoc-3.10.0-rc1-osx-x86_64.zip is attempted to be used to download the appropriate zip file.

If the `prototool.yaml` file looks like:
```yaml
protoc:
  version: 3.10.0-rc-1
```
then the URL https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0-rc-1/protoc-3.10.0-rc-1-osx-x86_64.zip is attempted to be used to download the appropriate zip file.

The URL to download protoc version is https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0-rc1/protoc-3.10.0-rc-1-osx-x86_32.zip. Notice the difference in .../v3.10.0-**rc1**/... and .../protoc-3.10.0-**rc-1**-osx-x86_32.zip. The hyphen location differs in the URL snippet and the zip file name, making it impossible to specify this protoc version in the `prototool.yaml` file.

**Comment by smaye81** [comment]
Yeah this is due to an anomaly in how the protoc download URL is formed.  We can add additional parsing for release candidates to remove the `-` for the subdomain portion of the URL.  

In the meantime, 3.10.0 is out so hopefully you are no longer blocked on this.

**Comment by smaye81** [comment]
This should be fixed by https://github.com/uber/prototool/pull/515

**Comment by alisonbelow** [comment]
Thank you!
