### ISSUE TITLE
Docker image for release 1.9.0 is missing

### ISSUE THREAD

**Issue by JorritSalverda** [uber/prototool#517]
The latest release at https://hub.docker.com/r/uber/prototool/tags is `1.8.1`. Can `1.9.0` be released there as well?

Thx for an awesome tool!

**Comment by carstenlenz** [comment]
It seems there is a `latest` tag published without one for the specific version?

**Comment by noorul** [comment]
When will be 1.9.0 available in docker hub?

**Comment by amwolff** [comment]
> It seems there is a `latest` tag published without one for the specific version?

The `latest` tag is indeed `1.9.0`:

```shell script
% docker run -i -t -v "$(pwd):/work" uber/prototool:latest /bin/bash
bash-5.0# prototool version
Version:                 1.9.0-dev
Default protoc version:  3.8.0
Go version:              go1.12.4
OS/Arch:                 linux/amd64
```

**Comment by noorul** [comment]
It is 1.9.0-dev

**Comment by smaye81** [comment]
Pushed 1.9.0 tonight.  Really sorry for the long delay.
