### ISSUE TITLE
Import "c.proto" was not found or had errors

### ISSUE THREAD

**Issue by new-commer** [uber/prototool#530]
I run into above error when formatting `a.proto`，below is the format command
```
./prototool --protoc-bin-path=/usr/protoc/bin/protoc --protoc-wkt-path=/usr/protoc/include format test
```
And below is he content if a.proto
```
syntax = "proto3";

package test.cc;

import "c.proto";

message exa {
  bool b = 1;
  c.simple s = 2;
  c.common k = 3;
}
```
`c.proto` is in the same directory with `a.proto` , And i warrant that `c.proto` is in the right format.

**Comment by new-commer** [comment]
It works after i moving `c.proto`  to `protoc-wkt-path` , how can i make it works that do not move `c.proto` ?

**Comment by asilverman** [comment]
@new-commer how did you resolve this issue?
