### ISSUE TITLE
[offtopic] how do you reuse generated code from another service?

### ISSUE THREAD

**Issue by AmsTaFFix** [uber/prototool#531]
great tool, and we migrate all microservice to your standard.
but, we have a question. what you do to use grpc client in another service?
we have service `store`
```
proto
  vendor
    store
      v1
        store_api.proto
        store.proto
    stock
      v1
        stock_api.proto
        stock.proto
```
`store` use files from `stock`

Now, we want to use `store` microservice in `webcam` microservice.
- We can copy and paste generated `go` code, but it won't work, because generated `go` code has invalid import path (`v1 "bitbucket.com/mic/store/internal/grpc/gen/go/vendor/store/stock/v1"`), it can't import, because valid import path should start from `bitbucket.com/mic/webcam`

we decided to make package `grpc_client`, where copy and paste all `proto` and make special `prototool.yaml`. And generate all clients in `webcam` microservice.

What the right way? Maybe the right way is generate all clients in place? (We only start integrate grpc, and have a lot of questions...)

**Comment by smaye81** [comment]
Can you pull in the proto repo to you `webcam` microservice as a Go dep (i.e. using glide, dep, or go modules)?
