### ISSUE TITLE
Lint rule to check package prefix

### ISSUE THREAD

**Issue by indysingh** [uber/prototool#533]
Hi,

I am using uber2 lint check in my project. I can see there is a java package prefix check already added but I am not able to find a way how can I enforce a check on package name?

Below is the example of what I am trying to achieve
prototool.yaml
lint:
  group: uber2
  package_prefix: test.abc.xyz

The package name in proto file should start with test.abc.xyz else it should throw an error.

Thanks

**Comment by smaye81** [comment]
The option is `java_package_prefix`.

See here for an example:  https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml

**Comment by smaye81** [comment]
Closing this issue.  If this is still a problem, please reopen.

**Comment by kostyay** [comment]
That option seems to only take effect with this rule:
`FILE_OPTIONS_EQUAL_JAVA_PACKAGE_PREFIX                         Verifies that the file option "java_package" is equal to PREFIX.PACKAGE, with PREFIX defaulting to "com" and configurable in your configuration file.`

It doesnt actually enforce the on the `package XXXX` inside a proto file
