### ISSUE TITLE
Latest Prototool Dockerfile using old version of grpc-gateway

### ISSUE THREAD

**Issue by jeffreyyong** [uber/prototool#553]
I'm using Prototool to generate some code related to grpc-gateway, however from this latest version of the [Dockerfile](https://hub.docker.com/r/uber/prototool/dockerfile), it seems like the plugin for grpc-gateway is using `GRPC_GATEWAY_VERSION=1.8.5` .

I would like to use [this particular template](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/internal/gengateway/template.go#L567) in the latest branch of grpc-gateway but it is not available in version `1.8.5`, I'm wondering if there's a way to change the version of the plugin in prototool configuration?

**Comment by smaye81** [comment]
We will be updating dependencies for the v1.11.0 release.  You can build your own Dockerfile based on the Prototool one in the meantime though, upgrading all necessary deps that you require.

**Comment by smaye81** [comment]
Closing in favor of https://github.com/uber/prototool/issues/558
