### ISSUE TITLE
version conversion

### ISSUE THREAD

**Issue by xufei56789** [uber/prototool#557]
**Problem reproduction**
execute:
docker run --rm -it -v $(pwd):/work uber/prototool:1.10.0 prototool generate
The generated prototool version is v1.3.1

**Expect**
prototool version is v1.2.1

**Comment by smaye81** [comment]
Do you mean protobuf version?  Not sure what you're actually saying here.

**Comment by xufei56789** [comment]
Is the protobuf version, How can I compile proto2?
