### ISSUE TITLE
Go get fails in dockerfile due to envoy dependency

### ISSUE THREAD

**Issue by stephenhyde** [uber/prototool#562]
Step 7/14 : RUN go get github.com/uber/prototool/cmd/prototool
 ---> Running in 0472a87cd7e6
package github.com/envoyproxy/go-control-plane/envoy/api/v2/core: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/core" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/core (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/core (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2 (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/service/load_stats/v2 (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/api/v2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2 (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2 (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/api/v2/route: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/route" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/route (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/api/v2/route (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2 (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2 (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2: cannot find package "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2 (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2 (from $GOPATH)
package github.com/envoyproxy/go-control-plane/envoy/type: cannot find package "github.com/envoyproxy/go-control-plane/envoy/type" in any of:
	/usr/local/go/src/github.com/envoyproxy/go-control-plane/envoy/type (from $GOROOT)
	/go/src/github.com/envoyproxy/go-control-plane/envoy/type (from $GOPATH)

**Comment by jesseobrien** [comment]
Can confirm I'm seeing this in multiple environments as well.

`OSX 10.15.5 (19F101)`
`go version go1.14.3 darwin/amd64`

and in docker in our CI pipeline

container image `golang:1.14`

**Comment by jesseobrien** [comment]
Looks like this PR is in to fix the issue. Just awaiting review 😄 

https://github.com/envoyproxy/go-control-plane/pull/312

**Comment by jesseobrien** [comment]
@stephenhyde that PR on envoyproxy has been merged, this is back to normal.

**Comment by stephenhyde** [comment]
Thanks for the update!
