### ISSUE TITLE
More alignment with grpcurl

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#6]
The library github.com/fullstorydev/grpcurl, built on top of github.com/jhump/protoreflect, enabled Prototool to get off-the-ground with gRPC support easily. However, Prototool does not implement all the features that grpcurl has. Right now:

- grpcurl has more features for gRPC (such as TLS) but requires you to generate `FileDescriptorSets` on your own if the gRPC reflection service is not available.
- Prototool handles `FileDescriptorSets` for you.

It'd be nice to merge this Venn diagram in some manner.

**Comment by peter-edge** [comment]
I think we should close this @amckinney @AlexAPB

**Comment by AlexAPB** [comment]
Yup, let's close it, we can add features as we see fit,  post 1.0
