### ISSUE TITLE
Fail to curl prototool > Failed writing body (0 != 16360)

### ISSUE THREAD

**Issue by ariden83** [uber/prototool#61]
Hello,

When I try to install protool, I've got this error: 

`curl -sSL https://github.com/uber/prototool/releases/download/v0.1.0/prototool-$(uname -s)-$(uname -m) \     
  -o /usr/local/bin/prototool && \
  chmod +x /usr/local/bin/prototool && \
  prototool -h`

return 

`curl: (23) Failed writing body (0 != 16360)`

**Comment by peter-edge** [comment]
Sorry to hear you're having trouble. Can you try `curl`ing something you know is there, like `https://google.com`? Does `/usr/local/bin` exist? Regardless, this is not a Prototool bug, so going to close this!
