### ISSUE TITLE
Mock gRPC servers

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#7]
The Protobuf team at Google had a request for a tool that brings up a mock gRPC server, given a Protobuf definition. It would spit back dummy data for any endpoint. This isn't overly difficult, but needs spec'ing out as to what this means (options to return errors? sizes of dummy data? etc).

**Comment by peter-edge** [comment]
I think this isn't necessary for v1.0 @amckinney @AlexAPB but will keep it up.

**Comment by peter-edge** [comment]
I'm going to close this as `wontfix` - working towards Inbox Zero and I don't think this is something we're going to get to

**Comment by pawanrawal** [comment]
We are building a mock server implementation as a proto plugin. You can give it a try at https://github.com/SafetyCulture/s12-proto/tree/master/protobuf/protoc-gen-gogrpcmock.
