### ISSUE TITLE
Formatter omits empty option incorrectly

### ISSUE THREAD

**Issue by johanbrandhorst** [uber/prototool#78]
When running `prototool format` on the following proto:

```protobuf
syntax = "proto3";

import "protoc-gen-swagger/options/annotations.proto";

option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
	info: {
		version: "1.0"
	}
	external_docs: {}
	schemes: HTTPS
};
```

It produces the following output:

```protobuf
syntax = "proto3";

import "protoc-gen-swagger/options/annotations.proto";

option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
	info: {
		version: "1.0"
	}
	external_docs:
	schemes: HTTPS
};
```

This does not compile with `protoc`, instead giving the error:

```bash
$  
test.proto: Error while parsing option value for "openapiv2_swagger": Expected "{", found "schemes".
```

The correct thing here would be to leave the `{}`.

**Comment by peter-edge** [comment]
Question: why does the key `external_docs` need to be outputted? Is it proto2 and required? Why is it correct to output it from the formatter, as opposed to drop it?

Figuring out the type of the value for `external_docs` and outputting `0, [], {}`, etc will be difficult.

**Comment by johanbrandhorst** [comment]
Well, it can be dropped, but if so the key should be dropped too. As it is it drops the value but not the key.
