### ISSUE TITLE
Command to output location of generated files

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#8]
Building on #2, there was a request from the Protobuf team at Google to derive the location of generated files for known plugins. For example, if you have `foo.proto`, used `protoc-gen-go`, and had an output directory of `../../gen/proto/go`, the list of generated files would be `["../../gen/proto/go/foo.pb.go"]`. This would help with integration into build systems.

**Comment by AlexAPB** [comment]
@peter-edge how were you envisioning exposing this? also, do you think this is still needed?

**Comment by peter-edge** [comment]
I'm going to close this as wontfix as doing this would mean Prototool would need to be much more plugin-aware than we ever intend to build it.
