### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#9]
There's a lot of `strings.HasPrefix` and `fmt.Sprintf("%s/%s", some, path)` lying around Prototool that needs to be cleaned up into `filepath.Join` etc calls. It's not that difficult, but just needs to be done.

**Comment by peter-edge** [comment]
This repository should be put onto https://www.appveyor.com for confirmation this works after fixed.

**Comment by peter-edge** [comment]
Not needed for v1.0 @amckinney @AlexAPB

**Comment by AlexAPB** [comment]
This may be unfavourable, but I'm fine with closing this issue; we can wait until the community puts pressure on us. We realistically won't get around to this anytime soon, since it's not much of an Uber priority.

**Comment by Groostav** [comment]
> the community puts pressure on us

I'd like to apply said pressure.

Building an API with protobuf, most of would-be users are Windows/C#/WPF app devs. What I'd like to do is write a little WPF app that wraps your command line utility with a couple buttons to run little prototool macros.

**Comment by stevemartinaws** [comment]
I would also like to see a windows version of this released. We are a a heavy .NET shop with a number of GRPC services. We have a few pain points with protoc and would like to make use of prototool's functionality

**Comment by peter-edge** [comment]
@Groostav @stevemartinaws if either of you would like to help out, we'd welcome a PR - #177 started the work but we are very inexperienced on the Windows side. Would appreciate any help you can give!

**Comment by peter-edge** [comment]
This has been open for a while, I haven't seen efforts to fix it - going to close for now. If someone has an effort to fix this, that'd be great, but we haven't gotten a lot more requests for it.
