### ISSUE TITLE
Standardize failures: Define identifiers, types, and constructor(s)

### ISSUE THREAD

**Issue by amckinney** [uber/prototool#92]
The `internal/text` package is primarily used in Prototool's proto compilation and lint processes. Seeing as this package is mostly concerned with instantiating `text.Failure`, we should standardize how they are represented. 

https://github.com/uber/prototool/pull/87 proposes several changes that should be considered at a later time. Specifically,

- Rename `text` to `failure` (motivated by https://blog.golang.org/package-names)
- Introduce a `failure.Type` to differentiate failures found in protoc vs. lint
- Remove unnecessary functionality (potentially `text.Failure.String` -- if not required)
- Introduce a `failure.LintIdentifier` enum so that lint IDs are not free-form strings.

These items can be largely ignored for the time being, but should be iterated on as we continue to develop out the protoc and lint processes.

**Comment by peter-edge** [comment]
@amckinney I think this is going to end up a "wontfix" cuz let's be honest, we'll never get to it heh - you cool if I close this? I want to get to Inbox Zero for Prototool at some point.

**Comment by peter-edge** [comment]
Closing, feel free to reopen if there's disagreement.
