### ISSUE TITLE
Behavior is confusing if you do not specify an argument for data for grpc

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#97]
Example: `cat input.json | prototool grpc example 0.0.0.0:8080 foo.ExcitedService/Exclamation`

The trailing `-` is missing to denote stdin reading, but this is technically a legal invocation where it assumes you mean the current directory, with address `example`, method name `0.0.0.0:8080`, and data `foo.ExcitedService/Exclamation`. We need to fix this in some manner, perhaps flags for the input args.

**Comment by peter-edge** [comment]
I'd propose `--address`, `--method`, `--data`, with either `--data -` for stdin, or another flag `--stdin` that we verify is not simultaneously specified with `--data`.

**Comment by AlexAPB** [comment]
I'm in favour of a `--stdin` flag instead of `--data -`; seems more intuitive to me.
