### ISSUE TITLE
Formatting order inconsistent with Google API Design Guidelines

### ISSUE THREAD

**Issue by johanbrandhorst** [uber/prototool#99]
Hi!

I'm raising this for discussion as I assume the formatting is already based on some formatting agreed within Uber. Anyway, the [Google API Design guidelines](https://cloud.google.com/apis/design/file_structure) explicitly list the following macro ordering:

The file structure must put higher level and more important definitions before lower level and less important items. In each proto file, the applicable sections should be in the following order:
1. Copyright and license notice if needed.
1. Proto syntax, package, option and import statements in that order.
1. The API overview documentation which prepares the readers for the rest of the file.
1. The API proto service definitions, in decreasing order of importance.
1. The RPC request and response message definitions, in the same order of the corresponding methods. Each request message must precede its corresponding response message, if any.
1. The resource message definitions. A parent resource must be defined before its child resource(s).

Now, I think specifically point 2 is violated by `prototool format` as it puts import statements above both options and package declarations.

**Comment by peter-edge** [comment]
Should be a pretty quick fix. Will do soon.

**Comment by peter-edge** [comment]
This is fixed on v0.3.0.
